server:
  port: 8081
  servlet:
    context-path: /admin

spring:
  profiles:
    active: local
#    active: dev
#    active: prod
    group:
      local: local-db
      dev: dev-db
      prod: prod-db
    include: db